### ISSUE TITLE
it ate my X

### ISSUE THREAD

**Issue by LiterallyVenom** [MrMilliganGHS/pyTTT2024#4] opened 2024-04-05 18:16 UTC
the code ate my X with O and there is no more X

**Comment by SickleStick** [comment] 2024-04-05 18:18
very miss leading name, I have found the same problem

**Comment by iangeekcode** [comment] 2024-04-05 18:21
You have no X

**Comment by MrMilliganGHS** [comment] 2024-04-09 17:50
Duplicate of #3

**Closed as completed by MrMilliganGHS** 2024-04-09 17:50 UTC
